// Auto-generated by starlight. Do not manually edit.

declare const backend: {
    /** backend/rpc_functions.lua:18 */
    getInstalledAppIds: () => Promise<string[]>;
    /** backend/rpc_functions.lua:34 */
    hasGameLua: (appid: string) => Promise<boolean>;
    /** backend/rpc_functions.lua:44 */
    validateApiKey: (api_key: string) => Promise<string>;
    /** backend/rpc_functions.lua:87 */
    getSettings: () => Promise<string>;
    /** backend/rpc_functions.lua:94 */
    clearSettings: () => Promise<string>;
    /** backend/rpc_functions.lua:104 */
    addToLibrary: (param1: unknown, param2: unknown) => Promise<string>;
    /** backend/rpc_functions.lua:117 */
    removeFromLibrary: (param1: unknown, param2: unknown) => Promise<string>;
};
