// Auto-generated by starlight. Do not manually edit.

declare const backend: {
    /** backend/rpc_functions.lua:22 */
    getInstalledAppIds: () => Promise<string[]>;
    /** backend/rpc_functions.lua:38 */
    hasGameLua: (appid: string) => Promise<boolean>;
    /** backend/rpc_functions.lua:48 */
    validateApiKey: (api_key: string) => Promise<string>;
    /** backend/rpc_functions.lua:85 */
    getSettings: () => Promise<string>;
    /** backend/rpc_functions.lua:92 */
    clearSettings: () => Promise<string>;
    /** backend/rpc_functions.lua:102 */
    addToLibrary: (param1: unknown, param2: unknown) => Promise<string>;
    /** backend/rpc_functions.lua:115 */
    removeFromLibrary: (param1: unknown, param2: unknown) => Promise<string>;
};
