// Auto-generated by starlight. Do not manually edit.

declare const backend: {
    /** backend/rpc_functions.lua:30 */
    getInstalledAppIds: () => Promise<string[]>;
    /** backend/rpc_functions.lua:46 */
    hasGameLua: (appid: string) => Promise<boolean>;
    /** backend/rpc_functions.lua:56 */
    validateApiKey: (api_key: string) => Promise<string>;
    /** backend/rpc_functions.lua:93 */
    getSettings: () => Promise<string>;
    /** backend/rpc_functions.lua:100 */
    clearSettings: () => Promise<string>;
    /** backend/rpc_functions.lua:110 */
    addToLibrary: (param1: unknown, param2: unknown) => Promise<string>;
    /** backend/rpc_functions.lua:123 */
    removeFromLibrary: (param1: unknown, param2: unknown) => Promise<string>;
};
